### PR TITLE
Turned playermat hider into a dropdown option

### PR DESCRIPTION
**Pull request by Chr1Z93**
Need to keep an open eye for any issues that stem from a removed mat.
Respawning a mat might eventually be added.

- updated GUID Reference Handler to allow edits to the index
- turned playermat hider into an option

closes https://github.com/argonui/SCED/issues/536

### CODE REVIEW

**Review by Entrox-Licher — CHANGES_REQUESTED** [review]
image
Produces error on startup.  Most likely an issue with script state?

**Comment by Chr1Z93** [comment]
> image Produces error on startup. Most likely an issue with script state?

I can't replicate that. The interceptor should be fully gone. How did you get that error?

**Comment by Entrox-Licher** [comment]
It's gone now!  Looks like the main merge fixed it?  (Or maybe I did something weird with Git haha?)

**Review by Entrox-Licher — CHANGES_REQUESTED** [review]
- Option should probably be under Playermat Settings
- Might want to change button (maybe even delete it?) once delete operation has been performed?

**Review by Entrox-Licher — APPROVED** [review]
Awesome!

**Pull request merged**
