### PR TITLE
Add card type tags to playermats

### PR DESCRIPTION
**Pull request by Buhallin**
Tags the main playmat slots as Asset, and the investigator as Investigator.  This matches the tagging on player cards so only the appropriate type of card will snap to those points.

### CODE REVIEW

**Comment by Chr1Z93** [comment]
Do we actually want this? Would stop all custom content from snapping (and even campaign assets like the partners from EotE)

**Comment by Buhallin** [comment]
> Do we actually want this? Would stop all custom content from snapping (and even campaign assets like the partners from EotE)

I'll leave the final call up to CZ, but I think we do.  If we're going to do more with card data, at some point it's going to break the custom content in some ways.  Snap points are a convenience (a major one, to be sure) so the lack of snapping isn't the end of the world.

I actually like this as a subtle way to nudge custom content towards the expectations in our brave new world.

**Comment by BootleggerFinn** [comment]
> > Do we actually want this? Would stop all custom content from snapping (and even campaign assets like the partners from EotE)
> 
> I'll leave the final call up to CZ, but I think we do. If we're going to do more with card data, at some point it's going to break the custom content in some ways. Snap points are a convenience (a major one, to be sure) so the lack of snapping isn't the end of the world.
> 
> I actually like this as a subtle way to nudge custom content towards the expectations in our brave new world.

I think we could probably do this in a way that doesn't break custom content snapping, though, and it's not realistic that existing custom content will all get updated.

Suppose the points restrict any cards _with metadata_ to snapping only if they have the right type, but any cards _without_ metadata will just snap indiscriminately.  This would reverse "the problem" so that custom content might snap when it shouldn't, which I think is a bit preferable since snapping can just be turned off for an individual card with a right-click.

**Comment by Buhallin** [comment]
Unfortunately, TTS's way to target snap points is very limited.  It can ONLY be by tags, so we can't do any kind of code check on it (like whether it has metadata).

**Comment by Chr1Z93** [comment]
Closed until we find a less conflicting solution

**Comment by Buhallin** [comment]
I had a tool to do this so I didn't have to click 50 snap points manually.  Maybe adding it to the player contribution bag is a decent choice?

**Comment by Chr1Z93** [comment]
> I had a tool to do this so I didn't have to click 50 snap points manually. Maybe adding it to the player contribution bag is a decent choice?

Yeah, that sounds like a good compromise

**Comment by argonui** [comment]
Looks good

**Review by argonui — APPROVED** [review]

**Review by Chr1Z93 — CHANGES_REQUESTED** [review]
There is a branch open for including this as function in the playmats (https://github.com/argonui/SCED/tree/playermat-tags) - this PR should not be merged

**Comment by Buhallin** [comment]
I think it still makes sense to merge this as the base version, since it's going to be the default?

**Comment by Chr1Z93** [comment]
> > There is a branch open for including this as function in the playmats (https://github.com/argonui/SCED/tree/playermat-tags) - this PR should not be merged
> 
> This doesn't make sense. We aren't long term having branches for features stay open. This pr should be merged.

I don't understand what the issue is? Why would we merge this while we are still having a discussion about this? Furthermore, we have a code freeze atm and this is far from a bug-fix.
I agree that this could be the default setting, but imo that should wait until we actually have an option panel to disable it.

What is the point in disabling the snapping for all custom cards right now?

**Comment by Buhallin** [comment]
So first, everyone chill.

This is being held because of the code freeze, no other reason.  I'm planning to submit it once 2.4 releases and we're clear to submit again.

We should submit this as the default.  We have accepted that new features will make some fan content work more erratically.  If we have the options panel in the same release to minimize that then great, but it should not block this PR because it's doing what we all agreed is fine to do.

**Review by Chr1Z93 — APPROVED** [review]

**Pull request merged**
