### PR TITLE
Removal of obsolete placeholder boxes for community content

### PR DESCRIPTION
**Pull request by Chr1Z93**
Because of the new download menu, we don't need these placeholders anymore.

### CODE REVIEW

**Review by Entrox-Licher — COMMENTED** [review]
Are the secret objectives/ultimatums in the download menu?

**Comment by Chr1Z93** [comment]
> Are the secret objectives/ultimatums in the download menu?

Oh that's a very good catch. Since they aren't, how about putting them in the fan-made accessories?

**Comment by Entrox-Licher** [comment]
Sounds good to me!

**Comment by Chr1Z93** [comment]
> Sounds good to me!

Updated!

**Review by Entrox-Licher — APPROVED** [review]

**Pull request merged**
