### PR TITLE
added numerical display and update button to cards with sealing

### PR DESCRIPTION
**Pull request by Chr1Z93**
Still WIP, unsure about the position / visual of the button

image

### CODE REVIEW

**Comment by argonui** [comment]
Can you add more context to why this change is needed?

**Comment by Chr1Z93** [comment]
> Can you add more context to why this change is needed?

Sure!

There are multiple cards that seal 5 or more tokens (Nephthys, Holy Spear, Rite of Sanctification etc.). For these cards you don't really know how many tokens exactly you have unless you count them manually (which can be a bit tedious). So this displays was meant as quick reference. The "click to update" ability is not really needed and could be removed if we don't value that.

**Comment by Chr1Z93** [comment]
@argonui I think I have a better solution: A tooltip that is displayed when hovering the card.

**Comment by argonui** [comment]
That sounds better. Balancing new features with existing players comforts is a tough one

**Comment by Chr1Z93** [comment]
I'll close this for now - I don't think there is demand for this

**Pull request closed without merging**
