### PR TITLE
Adding initial "The Feast of Hemlock Vale" cards

### PR DESCRIPTION
**Pull request by Chr1Z93**
image

This includes an update to the player card panel image:
image

### CODE REVIEW

**Comment by Tikatoy** [comment]
When these cards are in hand, Pitchfork front shows up as the player back image.

**Comment by Chr1Z93** [comment]
> When these cards are in hand, Pitchfork front shows up as the player back image. Screen Shot 2023-08-29 at 9 20 40 PM

Huh that's weird. I'll fix that. Thanks for catching that!

**Comment by Chr1Z93** [comment]
@Tikatoy fixed the Pitchfork back issue

**Comment by Tikatoy** [comment]
Looks good!

**Comment by Tikatoy** [comment]
Were you thinking of adding "I'll Pay You Back!" as well? There's only screenshots from the live stream so it would be low quality.

**Review by Tikatoy — APPROVED** [review]

**Comment by Chr1Z93** [comment]
Note to reader: "I'll Pay You Back!" will be added with the next batch of spoilered cards

**Pull request merged**
